[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
diesel = { version = "2.3.6", features = ["postgres", "chrono"] }
deadpool-diesel = { version = "0.6.1", features = ["postgres"] }
uuid = { version = "1.17.0", features = ["v4"] }
argon2 = "0.5.3"
rand_core = "0.10.0"
thiserror = "2.0.18"

[dev-dependencies]
diesel_migrations = { version = "2.3.2", features = ["postgres"] }
dotenvy = "0.15.7"
rand = "0.8"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
